version: '2'
services:
   db:
        image: postgres:12
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - 51515:5432
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        networks:
                - atlancis
   odoo:
        image:  odoo:16.0
        restart: always
        ports:
                - 8069:8069
                - 8072:8072
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - odoo-data:/var/lib/odoo
        networks:
                - atlancis
volumes:
        odoo-data:
        db-data:
networks:
        atlancis:
