version: '2'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - kadwekadb:/var/lib/postgresql/data/pgdata
  odoo15:
    image: odoo:16.0
    command: --dev=all
    ports:
      - 8089:8069
    links:
      - db:db
    volumes:
      - ./config:/etc/odoo
      - .:/mnt/extra-addons
      - kadwekaodoo:/var/lib/odoo
volumes:
  kadwekadb:
  kadwekaodoo:
  # fh29-jtbx-vkti